package org.glygen.tablemaker.persistence;

public enum TableMakerTable {
	GLYCAN,
	GLYCOPROTEIN,
	COLLECTION,
	GLYCANINCOLLECTION, 
	GLYCOPROTEININCOLLECTION,
	COC,
	METADATA,
	DATASET,
	DATASETMETADATA,
	DATASETGLYCOPROTEINMETADATA;
}
