spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/glygen
    username: glygen
    password: ENC(Y28YsnugTP2zFhN68Z12aHtODjqpm42tNcQ7WfJo/BI=)
    driver-class-name: org.postgresql.Driver
    separator: ^^^ END OF SCRIPT ^^^
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(vwVGR85Fa4BxyCrx/8nKdqhzeROIeMgzh9iZh/dd1jyt73xoytMx9zGFeu4byOsD94njLvFZUOf9sYvoPqhI1qcwh9LUmkEoSIBSbgp3qzguyQZT/6X8FA==)
            client-secret: ENC(6aOBrgpfQOh9LGVoIcr3UJCyBGHI1s5gcSm0IJxTwbK7Wy2P79W18lUkMvRbgmdS)
            scope: profile, email
            redirectUri: http://localhost:8080/login/oauth2/code/google
  mail:
    host: smtp.gmail.com
    port: 587
    username: glygenarray.api@gmail.com
    email: glygenarray.api@gmail.com
    password: ENC(jFt5gCSNcZv9uWa5yd+6gEFsZ6xmAu5pRkvdUgXY394=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  file:
    imagedirectory: ./images
    uploaddirectory: ./uploads

glytoucan:
  api-key: ENC(xxC0coU6Fo/mu1WTYjVA9IWdPerjRD0XPBEgmXgW8mdI6n7Jk5/bA3nFD48QKPxWpEVU9ICMXxlugIwk+DZSe65whHuRX8NhH0MwyeO2Xsc=)
  user-id: ff2dda587eb4597ab1dfb995b520e99b7ef68d7786af0f3ea626555e2c609c3d
  
github:
  token: ENC(0sa2VQ56p4vaj/IR39XUdq36LBs+qRBCHveywFoFz4e5+Y/+Pd4bymOtFD8oT6EHtCTjfclh3eY3WrVicOpIryY7koLGyhDNxBrnS7K3AJ+bG3HGLbxZMFngt5JW0SerwQz1is9RYEw=)
  issuesUrl: https://api.github.com/repos/glyspace/glyTableMaker-backend/issues
  repoUrl: https://github.com/glyspace/glyTableMaker-backend/issues
  assignee: senaarpinar, ReneRanzinger
  
glygen:
  oauth2:
     redirectUri: http://localhost:3000/oauth2/redirect
  scheme: http://
  host: localhost:8080
  basePath: /
  frontend:
      scheme: http://
      host: localhost:3000
      basePath: /
      emailVerificationPage: emailConfirmation