package org.glygen.tablemaker.persistence.glycan;

public enum MetadataType {
	BIOLOGICAL_SAMPLE,
	BIOLOGICAL_SAMPLE_BACKGROUND_ALTERATION,
	PROTEIN_MUTATION,
	PROTEIN_MUTATION_BACKGROUND_ALTERATION,
	EXPRESSED_PROTEIN,
	EXPRESSED_PROTEIN_ALTERED_SYSTEM,
	SYNTHETIC
}
